### ISSUE TITLE
Some questions about the data and the code about SEFEE

### ISSUE THREAD

**Issue by BurtonQin** [SayBender/SEFEE#2]
I really appreciate your amazing work “SEFEE: Lightweight Storage Error Forecasting in Large-Scale Enterprise Storage Systems”. I have carefully read the paper and the code, and I still have two questions about the target function in the paper, which are listed below.

![1](https://user-images.githubusercontent.com/11943383/133758763-43ead3f3-be3a-4425-8931-c6e04a262355.png)
1.	Code: I could not find the code corresponding to this target function. I could only find the call to `CP_ALS`, but not the target function.
https://github.com/SayBender/SEFEE/blob/e9005d562eab2a48b93511b79bf260a159b8cd8c/predictSEF.m#L74

2.	Data: I could not find the W, Y, and S in the data or code.
https://github.com/SayBender/SEFEE/blob/master/sampleData.mat
According to the paper, 
 
![2](https://user-images.githubusercontent.com/11943383/133758816-ec3ab21e-8696-4a90-a45b-4f47966d8762.png)

- 	The data in the sampleData.mat are not just 0 or 1. So sampleData.mat is not X. I guess you have multiplied X by W? Please help demonstrate the relationship between sampleData.mat and X.

-	Besides, I could not find Y. I wonder if it is hidden somewhere in sampleData.mat. Please help point out the source and usage of Y in the code.
-	The paper only mentions that S is an R-dim factorization vector for Y. How is S computed from Y? Or do we need to provide S? Please help point out the source and usage of S in the code.
 ![3](https://user-images.githubusercontent.com/11943383/133758844-3f0c5d24-e6ed-4d27-a3fd-42c0e8ed6f8a.png)

-	Could you provide the raw data which contains “error type ID” and its corresponding description and group?

**Comment by SayBender** [comment]
Dear @BurtonQin 
Thank you for your interest in our work,

1- I used CP_OPT (from CMTF toolbox) in the paper, because it uses side information and decomposes it coupled with the main tensor. Due to proprietary/confidentiality reasons I can not share the side information, so I only share the code for CP_ALS (from tensor toolbox) that is automatically used in the absence of side information.  S, Y and W  have to do with side information. Sample data is a 3D tensor (error,node,time) synthetically created to behave similarly to the actual data. 
However, Side information is contextual information about 1 or more dimensions in your data. So naturally It cannot be created synthetically. 

If you have your own side information and want to use it, you can integrate CP_OPT from CMTF toolbox in the code.
You can find CMTF_toolbox at: http://www.models.life.ku.dk/joda/CMTF_Toolbox (We used v1.1) CMTF toolbox is not an up-to-date toolbox, the publishers have not updated it since 2014. So we mostly base our experiments on tensor_toolbox (which don't use Side information) However, in paper we have done experiments with side information as well to show slight improvement over no side information.

2- About the sample data, it is actually using real values. They are not multiplied by anything. These are the actual number of errors in that time-slice. So if you want binary you can simply change all values above 1 to 1. 

This is deliberate, because our model works well, even with actual values. However, a slight improvement can be seen when using binary values.

 Y in that target equation is error severity which is the side information (context for error dimension) which I can't share. You can use the data to run CP_ALS without side information.

I believe I have answered your question, and as such I'm closing this issue, but let me know if you have further questions.
